name: Release

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build
      run: cargo build --release
  build-mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
    - name: build
      run: cargo build --release
