name: Release

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build - Mac
      uses: shogan/rust-musl-action@master
      with:
        args: cargo build --target x86_64-apple-darwin --release
    - name: Build - Linux
      uses: shogan/rust-musl-action@master
      with:
        args: cargo build --target x86_64-unknown-linux-musl --release
